import type { Metadata } from 'next'
import { Geist, Geist_Mono, Merriweather, Nunito, Press_Start_2P } from 'next/font/google'
import './globals.css'
import '@/styles/components.scss'
import '@/styles/room.scss'
import { ThemeProvider } from './_components/ThemeContext'
import AboutBookModal from './_components/AboutBookModal'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

const merriweather = Merriweather({
  variable: '--font-heading',
  subsets: ['latin'],
  weight: ['300', '400', '700', '900'],
})

const nunito = Nunito({
  variable: '--font-body',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
})

const pressStart2P = Press_Start_2P({
  variable: '--font-accent',
  subsets: ['latin'],
  weight: '400',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${merriweather.variable} ${nunito.variable} ${pressStart2P.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider>{children}</ThemeProvider>
        <AboutBookModal />
      </body>
    </html>
  )
}
